version: '2'
services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        restart: always
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8089"
        volumes:
            - /Users/zhongtenghui/monitor/influxdb:/var/lib/influxdb

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        expose:
            - "3000"

    cadvisor:
        image: google/cadvisor
        container_name: cadvisor
        ports: 
            - "8080:8080"
        links:
            - influxdb_exporter
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
        command:
            - -storage_driver=influxdb
            - -storage_driver_db=cadvisor
            - -storage_driver_host=nginx:6080

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - "9090:9090"
        links:
            - influxdb_exporter
        volumes:
            - /Users/zhongtenghui/monitor/prometheus.yml:/etc/prometheus/prometheus.yml
            - /Users/zhongtenghui/monitor/storage:/prometheus

    influxdb_exporter:
        image: neowaylabs/influxdb-exporter
        container_name: influxdb_exporter
        ports:
            - "9122:9122"

    nginx:
        image: ilagnev/alpine-nginx-lua
        container_name: nginx
        volumes:
            - /Users/zhongtenghui/monitor/nginx.conf:/etc/nginx/nginx.conf:ro
        links:
            - influxdb
            - influxdb_exporter
        ports:
            - "6080:6080"

